"""Notícias originais para regras de mesa; não são cartas oficiais da Estrela."""
EVENTS = [
('Bônus de produtividade','Seu trabalho foi reconhecido pela empresa.',1000),
('Restituição extra','Uma revisão encontrou imposto pago a mais.',1200),
('Venda na feira','Seu estande vendeu todos os produtos.',600),
('Prêmio de inovação','Sua ideia ganhou um concurso municipal.',1500),
('Freela concluído','Você entregou um projeto dentro do prazo.',800),
('Dividendo inesperado','Um investimento antigo distribuiu lucros.',1000),
('Objeto encontrado','Você devolveu um objeto e recebeu recompensa.',500),
('Cashback acumulado','Seus pontos foram convertidos em saldo.',400),
('Venda de bicicleta','Você vendeu uma bicicleta que não usava.',700),
('Consultoria','Uma empresa contratou sua orientação.',1400),
('Festival de bairro','Sua barraca foi um sucesso no festival.',900),
('Reembolso de viagem','A companhia devolveu uma cobrança indevida.',600),
('Patrocínio local','Uma loja apoiou seu projeto comunitário.',1100),
('Concurso de fotografia','Sua foto foi premiada.',800),
('Licenciamento','Você licenciou uma criação original.',1600),
('Venda de livros','Uma coleção antiga encontrou novo dono.',500),
('Seguro aprovado','Seu pedido de indenização foi aprovado.',1800),
('Curso ministrado','Você recebeu por ensinar uma habilidade.',1000),
('Economia de energia','Uma revisão devolveu valores da conta de luz.',400),
('Horta urbana','A venda da colheita gerou receita.',600),
('Aplicativo lançado','Seu pequeno aplicativo teve boas vendas.',1500),
('Antiguidade vendida','Um colecionador comprou uma peça antiga.',1300),
('Prêmio cultural','Seu projeto recebeu um incentivo cultural.',1700),
('Indicação profissional','Você recebeu uma comissão de indicação.',700),
('Pagamento atrasado','Um cliente finalmente quitou a dívida.',1100),
('Trabalho de fim de semana','Um serviço extra aumentou sua renda.',500),
('Ingresso reembolsado','Um evento cancelado devolveu seu dinheiro.',400),
('Venda de equipamento','Você vendeu um equipamento usado.',1200),
('Contrato renovado','Um cliente renovou seu contrato.',1400),
('Recompensa do bairro','Os moradores reconheceram sua ajuda.',600),
('Reembolso médico','O plano reembolsou uma consulta.',700),
('Promoção no trabalho','Você recebeu um bônus pela promoção.',1900),
('Arte encomendada','Uma encomenda de arte foi entregue.',900),
('Estacionamento cedido','Você alugou uma vaga por um período.',500),
('Juros recebidos','Uma aplicação fictícia gerou rendimento.',800),
('Acerto trabalhista','Você recebeu um acerto pendente.',2000),
('Aula particular','Suas aulas particulares renderam um extra.',600),
('Premiação esportiva','Sua equipe ganhou um torneio amador.',1000),
('Venda de móveis','Você vendeu móveis após reorganizar a casa.',1100),
('Evento organizado','A organização de um evento deu lucro.',1300),
('Pesquisa remunerada','Você participou de uma pesquisa.',300),
('Renda criativa','Uma coleção de adesivos teve boas vendas.',500),
('Reembolso bancário','Uma tarifa cobrada por engano foi devolvida.',300),
('Bônus de pontualidade','Sua equipe cumpriu todas as entregas.',700),
('Venda de domínio','Você vendeu um domínio que não utilizava.',1600),
('Oficina comunitária','Sua oficina recebeu inscrições pagas.',900),
('Campanha bem-sucedida','Uma campanha para seu negócio deu retorno.',1200),
('Encomenda especial','Uma grande encomenda foi concluída.',1800),
('Venda de mudas','Suas mudas fizeram sucesso no bairro.',400),
('Acerto de contas','Uma revisão revelou um crédito a seu favor.',1000),
('Conserto do carro','O carro precisou de manutenção urgente.',-1000),
('Conta de energia','Uma conta acumulada chegou para pagamento.',-1200),
('Reparo hidráulico','Um vazamento exigiu a visita de um encanador.',-600),
('Computador quebrado','Seu equipamento de trabalho precisou de reparo.',-1500),
('Viagem inesperada','Você precisou viajar para resolver um assunto.',-800),
('Multa de trânsito','Uma infração gerou uma multa.',-1000),
('Chave perdida','Foi necessário chamar um chaveiro.',-500),
('Tarifa anual','Uma assinatura anual foi renovada.',-400),
('Bicicleta danificada','A bicicleta precisou de novas peças.',-700),
('Consultoria contratada','Você contratou ajuda para seu negócio.',-1400),
('Evento cancelado','Parte dos custos do evento não foi reembolsada.',-900),
('Bagagem extraviada','Você precisou comprar itens essenciais.',-600),
('Equipamento alugado','Um serviço exigiu equipamento adicional.',-1100),
('Câmera em manutenção','A câmera precisou de um reparo.',-800),
('Licença de software','Você renovou ferramentas de trabalho.',-1600),
('Material de estudo','Você comprou livros e materiais.',-500),
('Franquia do seguro','Um sinistro exigiu pagamento da franquia.',-1800),
('Curso de atualização','Você se inscreveu em um curso profissional.',-1000),
('Lâmpadas e reparos','A iluminação precisou de manutenção.',-400),
('Jardim renovado','Você comprou materiais para o jardim.',-600),
('Servidor renovado','A hospedagem do seu projeto venceu.',-1500),
('Móvel restaurado','Um móvel antigo exigiu restauração.',-1300),
('Reforma da fachada','A fachada precisou de reparos.',-1700),
('Entrega urgente','Uma encomenda teve frete emergencial.',-700),
('Cobrança pendente','Uma conta esquecida precisou ser quitada.',-1100),
('Ferramenta substituída','Uma ferramenta de trabalho quebrou.',-500),
('Ingresso perdido','Você perdeu um ingresso sem reembolso.',-400),
('Equipamento novo','Foi preciso substituir um equipamento.',-1200),
('Contrato revisado','Uma revisão contratual teve custos.',-1400),
('Limpeza emergencial','Uma limpeza especial foi necessária.',-600),
('Consulta médica','Você teve uma despesa de saúde.',-700),
('Mudança de endereço','A mudança teve custos extras.',-1900),
('Material artístico','Você repôs materiais para uma encomenda.',-900),
('Estacionamento','Despesas de estacionamento se acumularam.',-500),
('Taxa administrativa','Uma regularização exigiu uma taxa.',-800),
('Acerto de fornecedor','Você quitou uma conta com um fornecedor.',-2000),
('Internet em manutenção','Foi necessário trocar equipamentos de rede.',-600),
('Uniformes da equipe','Sua equipe precisou de novos uniformes.',-1000),
('Móveis danificados','Um transporte danificou alguns móveis.',-1100),
('Reserva de salão','Você pagou a reserva de um salão.',-1300),
('Documento reemitido','Você pagou a emissão de uma segunda via.',-300),
('Embalagens novas','Seu negócio precisou repor embalagens.',-500),
('Taxa de serviço','Uma prestação de serviço teve taxa adicional.',-300),
('Entrega refeita','Um pedido precisou ser reenviado.',-700),
('Domínio renovado','Você renovou serviços do seu negócio.',-1600),
('Oficina reformada','A oficina precisou de manutenção.',-900),
('Campanha contratada','Você investiu em divulgação.',-1200),
('Compra de estoque','Você repôs o estoque do seu negócio.',-1800),
('Plantas substituídas','Uma tempestade danificou seu jardim.',-400),
('Acerto de despesas','Uma revisão revelou despesas pendentes.',-1000),
]
assert len(EVENTS)==100 and len({e[0] for e in EVENTS})==100
assert sum(e[2] for e in EVENTS)==0
